### ISSUE TITLE
change Roles 

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#101]
role2 soll zu Leitung umbenannt werden und parent = Member gesetzt werden.. da kracht der StatsService

**Comment by Fryday80** [comment]
'...\zend-servicemanager\src\ServiceManager.php:1092	source  Zend\ServiceManager\ServiceManager->createServiceViaCallback(arguments)

...\zend-servicemanager\src\ServiceManager.php:634	source  Zend\ServiceManager\ServiceManager->createFromFactory(arguments)

...\zend-servicemanager\src\ServiceManager.php:597	source  Zend\ServiceManager\ServiceManager->doCreate(arguments)

...\zend-servicemanager\src\ServiceManager.php:530	source  Zend\ServiceManager\ServiceManager->create(arguments)

D:\Web\Webprojekte\SRzA\module\Application\Module.php:17	source  Zend\ServiceManager\ServiceManager->get(arguments)

 7:    
 8:    class Module
 9:    {
10:        public function onBootstrap(MvcEvent $e)
11:        {
12:            $sm = $e->getApplication()->getServiceManager();
13:            date_default_timezone_set ("Europe/Berlin");
14:            $translator = $sm->get('translator');
15:            AbstractValidator::setDefaultTranslator($translator);
16:            $eventManager = $e->getApplication()->getEventManager();
17:            $statsService = $sm->get('StatisticService');
18:            $eventManager->attach('dispatch', array($statsService, 'onDispatch'));
19:            $eventManager->attach('dispatch.error', array($statsService, 'onError'));
20:            $eventManager->attach('finish', array($statsService, 'onFinish'));
21:            $systemService = $sm->get('SystemService');
inner-code	Application\Module->onBootstrap(arguments)

...\zend-eventmanager\src\EventManager.php:490	source  call_user_func(arguments)

...\zend-eventmanager\src\EventManager.php:251	source  Zend\EventManager\EventManager->triggerListeners(arguments)

...\vendor\zendframework\zend-mvc\src\Application.php:169	source  Zend\EventManager\EventManager->triggerEvent(arguments)

...\vendor\zendframework\zend-mvc\src\Application.php:281	source  Zend\Mvc\Application->bootstrap(arguments)

D:\Web\Webprojekte\SRzA\public\index.php:42	source  Zend\Mvc\Application::init(arguments)'

**Comment by Fryday80** [comment]
er kackt irgendwo bei der änderung ab.. die db einträge stimmen nicht in der roles tabelle

**Comment by Fryday80** [comment]
Namen Ändern war nicht das problem sonder parents ändern

**Comment by salt42** [comment]
sicher das des nur bei parent änderung passiert?
