### ISSUE TITLE
pw reset error

### ISSUE THREAD

**Issue by salt42** [Fryday80/SRzA#112]
Undefined variable: pwForm
...\SRzA\module\Auth\view\auth\auth\reset.phtml:6

kannst du mir mal erklären warum immer wieder sachen nicht mehr funktionieren, die schon funktioniert haben?

**Comment by Fryday80** [comment]
??? ich bekomm da keinen fehler...
auf master

**Comment by Fryday80** [comment]
live Branch auch ned

**Comment by Fryday80** [comment]
?? nichr reproduzierbar bei mir
