### ISSUE TITLE
Equipment Manager

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#119]
inject canvas tent drawing to tent show page?

**Comment by Fryday80** [comment]
equip table soweit ausgedünnt

**Comment by salt42** [comment]
ich dachte des jetzt eigentlich so das man den plan zu nem jpg macht und man dann nur die bilder anzeigt und wir nicht noch ein viewer bauen müssen

**Comment by Fryday80** [comment]
wenn man das gezeichnete objekt als jpg irgendwo speichert und dann hat.... ist das vom handling deutlich einfacher...

**Comment by salt42** [comment]
die equipmanager module.config.php geht so nicht.
1. da dürfen keine funktionen drin sein!
2. die config is global in die du da schreibst, also keys überschreiben sich wenn du die selben in nem anderen modul benutz
3. die config solte schlank bleiben

**Comment by Fryday80** [comment]
1. ok, die functionen sind u.u. eh deprecated... muss ich nochmal schauen
2. die sollten sich nicht überschreiben, da ich ja den Modulnamen als Key hab
3. wo verdammt noch mal soll das denn dann hin? die daten da rein bekommen tut man ja auf x-tausend wegen... das was mir spontan an "sinnvollen" stellen einfällt ist
* eben die config
* es im controller constructor zu includen
