### ISSUE TITLE
Content->bearbeiten->Quellcode bearbeiten --><span> nach erneutem aufrufen weg?

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#13]
content -> Quellcode bearbeiten (html tags einbauen) -> update => funzt
erneut bearbeiten -> html tags alle wieder weg

**Comment by salt42** [comment]
wenn zwischen dem tag nix steht ist das denk ich gewolt (http://stackoverflow.com/questions/18261198/ckeditor-removing-empty-span-automatically)

eventuel findet man was in den docs  -> http://docs.ckeditor.com

**Comment by Fryday80** [comment]
<div> geht, aber nicht verschachtelt
