### ISSUE TITLE
equipmentService

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#16]
neue Tabelle => tent (
usr-id | type | shape | length | width | spares
Bsp.: 
xy, Alex, rund, 4m, -, 2 Schlafplätze
yx, sonstige, 4-Eck, 6m, 4m, 0/voll

**Comment by salt42** [comment]
class tent:
owner (? du hast user-id geschrieben, soll des der besitzer sein?)
type (muss man die typen auch verwalten können? oder einfach als string reinschreiben?)
shape, length, width and space (des sind ja eigentlich die eigenschaften vom zelt typ)

**Comment by Fryday80** [comment]
oh sorry, ohne sich bei den zelten auszukennen war das kacke zu verstehen und ne (Tent-) id fehlt natürlich auch:
Bsp. meine Zelte (usr_id 1)
1 | 1 | sonstige | 4-Eck | 4m | 2m | 0/voll
2 | 1 | Alex        | rund  | 4m |       | 4 Schlafplätze 
_______________________________________________________________
das war auch nur mal schnell hingeschrieben, muss das nochmal durcharbeiten, 
und ja die zelt-typen wären ganz nice zu verwalten/bearbeiten (es gibt halt v.a. so 4-5 standard zelte und von denen teilweise verschiedene größen und höhen), aber erst mal reicht n string
und length etc sind eigenschaften, ja ...
ich hätte mir gedacht das als objekt in php zu bauen... wobei in dem fall ja eigentlich n simples array reicht
