### ISSUE TITLE
accordion animation is am sack

### ISSUE THREAD

**Issue by salt42** [Fryday80/SRzA#17]
zb. auf "für veranstalter" -> "angebot".
hast du da was an dem css gemacht das des nicht mehr sauber animiert oder ist des nur bei mir so?

**Comment by Fryday80** [comment]
ist bei mir auch,
ich hab da was am css machen müssen, weil das mit bg icons und margin, padding nicht stimmte
overrides sind in der _accordion.less im less ordner

**Comment by Fryday80** [comment]
css overrides erledigt und js befehl umgezogen
