### ISSUE TITLE
wir brauchen noch

### ISSUE THREAD

**Issue by salt42** [Fryday80/SRzA#24]
bilder
-- standart bild fals eins wirklich nicht gefunden wurde
-- standart vorschaubild

**Comment by Fryday80** [comment]
vorerst ein burg-clipart (defalt.png) und ein drachenbild (default2.png) in den default ordner gepackt

**Comment by Fryday80** [comment]
img not found hinzugefügt

**Comment by Fryday80** [comment]
noPreviewPic hinzugefügt,
nicht schön aber erst mal reicht es
