### ISSUE TITLE
DataTableHelper object usage

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#33]
Application > ... >DataTableHelper.php
line 67

kennst du nen Fall wo wir da objekte nutzen? bzw stimmt der code auf der objekt-seite überhaupt?

wenn der so stimmt, ist da ja mega viel überflüssiger code

**Comment by salt42** [comment]
aber is doch schön das wir es können... las drin

**Comment by Fryday80** [comment]
du hast mich falsch verstanden, ich wills ned löschen, sondern nur schöner / kürzer bauen, die frage ist ob der code so passt... du hast mehr plan von deinen Objekten/ modulen &co...

ich kürze das mal
