### ISSUE TITLE
FileBrowser delete new created folder

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#34]
funzt ned 

`ErrorException: unlink(D:/Web/Webprojekte/SRzA/Data/gallery/default/Mein_Ordner): Permission denied in D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php:376
Stack trace:
#0 [internal function]: Tracy\Debugger::errorHandler(2, 'unlink(D:/Web/W...', 'D:\\Web\\Webproje...', 376, Array)
#1 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php(376): unlink('D:/Web/Webproje...')
#2 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(563): Media\Service\MediaService->deleteItem('/gallery/defaul...')
#3 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(199): Media\Controller\FileBrowserController->actionDelete()
#4 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(38): Media\Controller\FileBrowserController->handleRequest()
#5 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): Media\Controller\FileBrowserController->actionAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 D:\Web\Webprojekte\SRzA\public\index.php(45): Zend\Mvc\Application->run()
#16 {main}
Unable to log error: Directory is not specified.
errorexception: unlink(D:/Web/Webprojekte/SRzA/Data/gallery/default/Mein_Ordner): Permission denied in D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php:376Stack trace:#0 [internal function]: Tracy\Debugger::errorHandler(2, 'unlink(D:/Web/W...', 'D:\\Web\\Webproje...', 376, Array)#1 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php(376): unlink('D:/Web/Webproje...')#2 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(563): Media\Service\MediaService->deleteItem('/gallery/defaul...')#3 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(199): Media\Controller\FileBrowserController->actionDelete()#4 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(38): Media\Controller\FileBrowserController->handleRequest()#5 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): Media\Controller\FileBrowserController->actionAction()#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))#7 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#8 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#9 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#10 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))#12 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#13 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#14 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#15 D:\Web\Webprojekte\SRzA\public\index.php(45): Zend\Mvc\Application->run()#16 {main}Unable to log error: Directory is not specified.
errorexception: unlink(D:/Web/Webprojekte/SRzA/Data/gallery/default/Mein_Ordner): Permission denied in D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php:376Stack trace:#0 [internal function]: Tracy\Debugger::errorHandler(2, 'unlink(D:/Web/W...', 'D:\\Web\\Webproje...', 376, Array)#1 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php(376): unlink('D:/Web/Webproje...')#2 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(563): Media\Service\MediaService->deleteItem('/gallery/defaul...')#3 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(199): Media\Controller\FileBrowserController->actionDelete()#4 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(38): Media\Controller\FileBrowserController->handleRequest()#5 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): Media\Controller\FileBrowserController->actionAction()#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))#7 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#8 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#9 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#10 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))#12 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#13 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#14 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#15 D:\Web\Webprojekte\SRzA\public\index.php(45): Zend\Mvc\Application->run()#16 {main}Unable to log error: Directory is not specified.errorexception: unlink(D:/Web/Webprojekte/SRzA/Data/gallery/default/Mein_Ordner): Permission denied in D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php:376Stack trace:#0 [internal function]: Tracy\Debugger::errorHandler(2, 'unlink(D:/Web/W...', 'D:\\Web\\Webproje...', 376, Array)#1 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php(376): unlink('D:/Web/Webproje...')#2 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(563): Media\Service\MediaService->deleteItem('/gallery/defaul...')#3 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(199): Media\Controller\FileBrowserController->actionDelete()#4 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(38): Media\Controller\FileBrowserController->handleRequest()#5 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): Media\Controller\FileBrowserController->actionAction()#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))#7 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#8 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#9 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#10 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))#12 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#13 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#14 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#15 D:\Web\Webprojekte\SRzA\public\index.php(45): Zend\Mvc\Application->run()#16 {main}Unable to log error: Directory is not specified.
errorexception: unlink(D:/Web/Webprojekte/SRzA/Data/gallery/default/Mein_Ordner): Permission denied in D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php:376Stack trace:#0 [internal function]: Tracy\Debugger::errorHandler(2, 'unlink(D:/Web/W...', 'D:\\Web\\Webproje...', 376, Array)#1 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php(376): unlink('D:/Web/Webproje...')#2 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(563): Media\Service\MediaService->deleteItem('/gallery/defaul...')#3 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(199): Media\Controller\FileBrowserController->actionDelete()#4 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(38): Media\Controller\FileBrowserController->handleRequest()#5 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): Media\Controller\FileBrowserController->actionAction()#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))#7 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#8 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#9 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#10 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))#12 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#13 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#14 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#15 D:\Web\Webprojekte\SRzA\public\index.php(45): Zend\Mvc\Application->run()#16 {main}Unable to log error: Directory is not specified.errorexception: unlink(D:/Web/Webprojekte/SRzA/Data/gallery/default/Mein_Ordner): Permission denied in D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php:376Stack trace:#0 [internal function]: Tracy\Debugger::errorHandler(2, 'unlink(D:/Web/W...', 'D:\\Web\\Webproje...', 376, Array)#1 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php(376): unlink('D:/Web/Webproje...')#2 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(563): Media\Service\MediaService->deleteItem('/gallery/defaul...')#3 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(199): Media\Controller\FileBrowserController->actionDelete()#4 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(38): Media\Controller\FileBrowserController->handleRequest()#5 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): Media\Controller\FileBrowserController->actionAction()#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))#7 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#8 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#9 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#10 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))#12 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#13 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#14 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#15 D:\Web\Webprojekte\SRzA\public\index.php(45): Zend\Mvc\Application->run()#16 {main}Unable to log error: Directory is not specified.errorexception: unlink(D:/Web/Webprojekte/SRzA/Data/gallery/default/Mein_Ordner): Permission denied in D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php:376Stack trace:#0 [internal function]: Tracy\Debugger::errorHandler(2, 'unlink(D:/Web/W...', 'D:\\Web\\Webproje...', 376, Array)#1 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php(376): unlink('D:/Web/Webproje...')#2 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(563): Media\Service\MediaService->deleteItem('/gallery/defaul...')#3 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(199): Media\Controller\FileBrowserController->actionDelete()#4 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(38): Media\Controller\FileBrowserController->handleRequest()#5 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): Media\Controller\FileBrowserController->actionAction()#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))#7 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#8 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#9 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#10 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))#12 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#13 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#14 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#15 D:\Web\Webprojekte\SRzA\public\index.php(45): Zend\Mvc\Application->run()#16 {main}Unable to log error: Directory is not specified.errorexception: unlink(D:/Web/Webprojekte/SRzA/Data/gallery/default/Mein_Ordner): Permission denied in D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php:376Stack trace:#0 [internal function]: Tracy\Debugger::errorHandler(2, 'unlink(D:/Web/W...', 'D:\\Web\\Webproje...', 376, Array)#1 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Service\MediaService.php(376): unlink('D:/Web/Webproje...')#2 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(563): Media\Service\MediaService->deleteItem('/gallery/defaul...')#3 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(199): Media\Controller\FileBrowserController->actionDelete()#4 D:\Web\Webprojekte\SRzA\module\Media\src\Media\Controller\FileBrowserController.php(38): Media\Controller\FileBrowserController->handleRequest()#5 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): Media\Controller\FileBrowserController->actionAction()#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))#7 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#8 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#9 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#10 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))#12 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))#13 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#14 D:\Web\Webprojekte\SRzA\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))#15 D:\Web\Webprojekte\SRzA\public\index.php(45): Zend\Mvc\Application->run()#16 {main}Unable to log error: Directory is not specified. `

**Comment by salt42** [comment]
dein Data folder hat die falschen rechte. mach einfach jeder vollzugriff drauf
