### ISSUE TITLE
FileBrowser conf files exclude exept admin / standards

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#35]
standard einstellung der conf files auf only admin (wenn nicht schon gemacht)

**Comment by salt42** [comment]
im Moment muss man sie durch kopieren oder hochladen erstellen. und da immer des nächst höhere gesucht wird machts auch keinen sinn mit jedem folder eine conf zu erstellen.

**Comment by Fryday80** [comment]
will be fixed in issue #44
