### ISSUE TITLE
FileBrowser move denied file

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#38]
man kann verbotene Files kopieren und moven, wenn man den ordner verschiebt/kopiert

**Comment by Fryday80** [comment]
löschen geht nicht

**Comment by salt42** [comment]
da man die rechte auch mit verschiebt und kopiert is des nich so schlimm. aber wenn du es anders haben willst, schlag ich vor das nur die ordner rechte zählen und nich die datei restrictions. also dass kein ordner drin sein darf für den man nicht die richtigen rechte hat.
