### ISSUE TITLE
bitte mal anschauen -> js optimierung

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#50]
https://github.com/requirejs/example-multipage
https://github.com/requirejs/example-multipage-shim
doc
http://requirejs.org/docs/start.html

**Comment by Fryday80** [comment]
die docu ist mir zwar -beim schnell drüberfliegen- etwas zu complex (checks halt ned so ganz) aber das kann man ja ändern^^^

**Comment by salt42** [comment]
ne des machen wir anderes. requirejs is zwar ganz nett aber bei bisal scheiße einzubauen.
