### ISSUE TITLE
sammel issue

### ISSUE THREAD

**Issue by salt42** [Fryday80/SRzA#81]
ich hab mal alles unter "webmaster" durchgeklickt -> das sind die issues
- ~~dashboard~~
- ~~perm/edit - wenn man nix auswählt und trotzdem auf add clickt~~
- ~~resource/delete - codierungs fehler~~
- ~~role/add - error~~
- ~~role/delete - nicht getested~~
- ~~role/edit - error~~
- ~~User/add - error  -> Integrity constraint violation: 1048 Column 'created_on' cannot be null~~
- ~~UserForm - form ele "geburstag" solte vom typ "date" sein~~
- ~~UserForm - form ele "postleitzahl" solte vom typ "number" sein~~

alles unter admin
- ~~castmanager/wappen/edit - Daten aus db einfügen !NEU!~~
- ~~castmanager/wappen/edit - wenn bild muss leer sein dürfen beim editieren~~
- ~~castmanager/families/add - geht ürgendwie nich~~ klar wenn du das auskommentierst^^
- ~~castmanager/families/delete - nicht getested~~ geht
- ~~castmanager/characters/ - error in der dataTable~~
- nav -> nav sort 
-- add Item wirft deprecated issue 
-- add geht nicht

**Comment by Fryday80** [comment]
* dashboard check

**Comment by salt42** [comment]
codierungsfehler is wenn du äüö hast du da so komische zeichen draus werden
