### ISSUE TITLE
Basic Tactics Sammelthread

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#86]
* **Services**
** sollen wir je Table einen Service bauen und je Controller (wenn noch einer nötig ist) der alle Tables zusammenfängt bzw. wenn es sich anbietet einen Service für mehrere Controller
Also diese Struktur:
Table1->ServiceTable1
Table2->ServiceTable2---->ServiceController-->Controller (falls es sich anbietet Contr.2, Contr.3)
Table3->ServiceTable3
* **CSS**
** Issue #64 
* **Performance/genaral usage**
** wenn eine Table/ein Service nur 1x an einer stelle genutzt wird, macht es sinn statt der Table/den Service nur diese Daten in der Factory zu übergeben? (bsp. siehe CalendarService roleTable hier wird genau 1x ->getAllRoles() ausgeführt, das könnte man ja direkt übergeben, dann ist der db zugriff in den Init bereich bei erstaufruf geschoben, statt bei jedem calendar aufruf)

**Comment by salt42** [comment]
auf keinen fall für jede table nen service!
und was die performance angeht, ne des machen wir wenn anders. des is auch alles nich des problem. las mal die performance meine sorge sein.
und an dem css hab ich nichts auszusetzen, da is alles da wo es sein soll, gerade was die inlinescript files angeht.
