### ISSUE TITLE
Char - backend

### ISSUE THREAD

**Issue by Fryday80** [Fryday80/SRzA#92]
* edit geht nicht  ---> ambigious... SQL

**Comment by Fryday80** [comment]
ohne where kommt aber das raus:
`
array(8) {
  [0]=>
  array(15) {
    ["id"]=>
    string(1) "2"
    ["user_id"]=>
    string(1) "2"
    ["name"]=>
    string(3) "Fry"
    ["surename"]=>
    string(7) "zu Leym"
    ["gender"]=>
    string(1) "m"
    ["birthday"]=>
    string(10) "1748-04-07"
    ["guardian_id"]=>
    string(1) "0"
    ["supervisor_id"]=>
    string(1) "1"
    ["vita"]=>
    string(7) "jgfjjdj"
    ["active"]=>
    string(1) "1"
    ["family_id"]=>
    string(1) "2"
    ["family_name"]=>
    string(7) "zu Leym"
    ["blazon_id"]=>
    string(1) "3"
    ["job_id"]=>
    string(1) "1"
    ["job_name"]=>
    string(6) "Ritter"
  }`

**Comment by salt42** [comment]
der fehler is eigentlich ganz einfach. in deinem sql ist 'id' mehrdeutig. des passiert nur bei join's, weil sonst kanns ja es ja nur eine id geben.
aber da wir joinen und bei uns fast jede tabele eine id hat, muss man halt im sql anstatt id halt TABLE.id machen. wobei TABLE der tabellen name ODER der alias des tabellen namens ist.
